### ISSUE TITLE
Proposal: Change `defattributes` to `content_schema`

### ISSUE THREAD

**Issue by dlederle** [vigetlabs/colonel_kurtz_ex#4]
Currently a block defines the content attributes like:
```elixir
defattributes(
  src: :string,
  width: :integer,
  height: :integer
)
```

I propose we change the macro to mirror ecto:

```elixir
content_schema do
  field :src, :string
  field :width, :integer
  field :height, :integer
end
```

This syntax is familiar in the community and is pretty close to whats actually happening on the backend when it gets turned into an embedded schema.

**Comment by solomonhawk** [comment]
This proposal is out of date. We decided to more closely adhere to `Ecto.Schema` and as a result #7 changed our API to just use `embedded_schema`.
